[package]
name = "share"
version = "0.1.0"
authors = ["stf"]

[dependencies]
bitfield = "0.12.0"
bitflags = "0.9.1"
spin = "0.4.5"
x86_64 = "0.1.2"
multiboot = "0.2.0"
x86 = "0.8.1"
rlibc = "1.0"

[features]
setup = []
vmm = []
debug_paging = []
debug_vmread = []
debug_vmwrite = []
